services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3307:3306"
    volumes:
      - $HOME/Desktop/MySQL-Snippets/carpooling.sql:/carpooling.sql
